# Generated by Django 4.2.16 on 2026-03-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('languages', 'Programming Languages'), ('frameworks', 'Frameworks & Libraries'), ('tools', 'Tools & Software')], default='languages', max_length=20),
        ),
    ]
