# Generated by Django 4.2.16 on 2026-03-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('languages', 'Languages'), ('frontend', 'Front-End'), ('backend', 'Back-End Frameworks'), ('databases', 'Databases'), ('tools', 'Tools & Software')], default='languages', max_length=20),
        ),
    ]
